-- harpoon keymaps --
vim.keymap.set("n", "<leader>ha", require("harpoon.mark").add_file)
vim.keymap.set("n", "<leader>hf", require("harpoon.ui").toggle_quick_menu)
vim.keymap.set("n", "<leader>hu", require("harpoon.ui").nav_next)
vim.keymap.set("n", "<leader>hd", require("harpoon.ui").nav_prev)
vim.keymap.set("n", "1", ":lua require('harpoon.ui').nav_file(1)<CR>")
vim.keymap.set("n", "2", ":lua require('harpoon.ui').nav_file(2)<CR>")
vim.keymap.set("n", "3", ":lua require('harpoon.ui').nav_file(3)<CR>")
vim.keymap.set("n", "4", ":lua require('harpoon.ui').nav_file(4)<CR>")
vim.keymap.set("n", "5", ":lua require('harpoon.ui').nav_file(5)<CR>")
vim.keymap.set("n", "6", ":lua require('harpoon.ui').nav_file(6)<CR>")
vim.keymap.set("n", "7", ":lua require('harpoon.ui').nav_file(7)<CR>")
vim.keymap.set("n", "8", ":lua require('harpoon.ui').nav_file(8)<CR>")
vim.keymap.set("n", "9", ":lua require('harpoon.ui').nav_file(9)<CR>")
